### ISSUE TITLE
Got `sqlite3.IntegrityError` during scraping

### ISSUE THREAD

**Issue by kmate** [datapao/dac#30]
Stack trace:
```
Exception in thread scraping-loop-Thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1229, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 577, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: cluster_types.type

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/scraping/scraper.py", line 440, in scraping_loop
    result = scrape(json_path, session)
  File "/app/scraping/scraper.py", line 462, in scrape
    instance_types = upsert_instance_types(session)
  File "/app/scraping/scraper.py", line 138, in upsert_instance_types
    session.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2470, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2568, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1084, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1229, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 577, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: cluster_types.type
[SQL: INSERT INTO cluster_types (scrape_time, type, cpu, mem, dbu_light, dbu_job, dbu_analysis) VALUES (?, ?, ?, ?, ?, ?, ?)]
```

**Comment by gulyasm** [comment]
Thanks for submitting this, we'll look into this!

**Comment by kmate** [comment]
Just checking, could you make any progress on this one recently?

**Comment by fulibacsi** [comment]
Hey @kmate! I just started working on the issue. Solution should be available later today.

**Comment by fulibacsi** [comment]
Solution available at master branch now.

**Comment by kmate** [comment]
Wow, thanks!

**Comment by kmate** [comment]
I might still have some problems:
```
2020-07-13 16:31:31,794 dac          INFO     Command: scrape
2020-07-13 16:31:31,794 dac          DEBUG    Config loaded from: configs/config.json
2020-07-13 16:31:31,799 dac-scraper  INFO     loop will go into another scraping
2020-07-13 16:31:31,799 dac-scraper  INFO     Scraping started...
2020-07-13 16:31:31,799 dac-scraper  DEBUG    Instance type scraping started...
2020-07-13 16:31:31,807 dac-scraper  DEBUG    Empty DB, scraping instance types...
2020-07-13 16:31:32,097 werkzeug     INFO      * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Exception in thread scraping-loop-Thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1229, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 577, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: cluster_types.type

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/scraping/scraper.py", line 440, in scraping_loop
    result = scrape(json_path, session)
  File "/app/scraping/scraper.py", line 462, in scrape
    instance_types = upsert_instance_types(session)
  File "/app/scraping/scraper.py", line 138, in upsert_instance_types
    session.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2470, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2568, in _flush
    flush_context.execute()
```

**Comment by kmate** [comment]
Here
```
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: cluster_types.type
[SQL: INSERT INTO cluster_types (scrape_time, type, cpu, mem, dbu_light, dbu_job, dbu_analysis) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: (('2020-07-13 16:31:33.732897', 'm4.large', 2, 8.0, 0.4, 0.4, 0.4), ('2020-07-13 16:31:33.732897', 'm4.xlarge', 4, 16.0, 0.75, 0.75, 0.75), ('2020-07-13 16:31:33.732897', 'm4.2xlarge', 8, 32.0, 1.5, 1.5, 1.5), ('2020-07-13 16:31:33.732897', 'm4.4xlarge', 16, 64.0, 3.0, 3.0, 3.0), ('2020-07-13 16:31:33.732897', 'm4.10xlarge', 40, 160.0, 3.86, 8.0, 8.0), ('2020-07-13 16:31:33.732897', 'm4.16xlarge', 64, 256.0, 3.86, 12.0, 12.0), ('2020-07-13 16:31:33.732897', 'm5.large', 2, 8.0, 0.35, 0.35, 0.35), ('2020-07-13 16:31:33.732897', 'm5.xlarge', 4, 16.0, 0.69, 0.69, 0.69)  ... displaying 10 of 146 total bound parameter sets ...  ('2020-07-13 16:31:33.732897', 'Standard_NC12s_v3', 12, '224.00 GiB', 10.0, 10.0, 10.0), ('2020-07-13 16:31:33.732897', 'Standard_NC24s_v3', 24, '448.00 GiB', 20.0, 20.0, 20.0))]
(Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by fulibacsi** [comment]
Looking at the traceback it seems like that it is running without the changes. Could you please check that? Meanwhile I try to replicate the error.

**Comment by kmate** [comment]
Sorry for the late reply. Indeed it works, somehow I missed the last commit from the version I ran....
